[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
fuzz_runs = 256

[rpc_endpoints]
local = "http://127.0.0.1:8545"
unit_zero_testnet = "https://rpc-testnet.unit0.dev"
unit_zero_mainnet = "https://rpc.unit0.dev"